# Generated by Django 5.1.4 on 2024-12-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_name',
            field=models.CharField(default='Old Car', max_length=100),
        ),
    ]
